### ISSUE TITLE
*

### ISSUE THREAD

**Issue by D-baj** [codevjs/Shopee-Flash-Sale-Bot#1]
Bot ini masih work nggak ya...?

Terima kasih

**Comment by codevjs** [comment]
Untuk sekarang work tapi masih lambat dalam melakukan proses order. saya akan segera mengupdate bot versi terbaru terimakasih

**Comment by D-baj** [comment]
> Untuk sekarang work tapi masih lambat dalam melakukan proses order. saya akan segera mengupdate bot versi terbaru terimakasih

Untuk menajalan kan bot ny apakah hanya dengan run index.js?
